# Generated by Django 2.2.2 on 2019-06-29 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onetoone', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='onetonetest',
            new_name='onetoonetest',
        ),
    ]
