# Generated by Django 2.2.2 on 2019-06-27 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='myfield',
            field=models.IntegerField(default=0),
        ),
    ]
