# Generated by Django 2.2.2 on 2019-06-28 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_ox'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ox',
            options={'ordering': ['-horn_length'], 'verbose_name_plural': 'oxen'},
        ),
    ]
