# Generated by Django 2.2.2 on 2019-06-28 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manytomany', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test',
        ),
    ]
